In [1]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import math
from sklearn.cross_validation import train_test_split,KFold
import numpy as np

C:\Users\DX\Anaconda3\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [2]:
df=pd.read_csv('Consumer_Complaints_train.csv')

In [3]:
df.head()

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Consumer consent provided?,Submitted via,Date sent to company,Company response to consumer,Timely response?,Consumer disputed?,Complaint ID
0,2014-05-15,Credit card,NaN,Billing statement,NaN,NaN,NaN,Wells Fargo & Company,MI,48342,Older American,NaN,Web,2014-05-16,Closed with explanation,Yes,No,856103
1,2014-09-18,Bank account or service,(CD) Certificate of deposit,"Making/receiving payments, sending money",NaN,NaN,NaN,Santander Bank US,PA,18042,NaN,NaN,Referral,2014-09-24,Closed,Yes,No,1034666
2,2014-03-13,Credit reporting,NaN,Incorrect information on credit report,Account status,NaN,NaN,Equifax,CA,92427,NaN,NaN,Referral,2014-04-03,Closed with non-monetary relief,Yes,No,756363
3,2015-07-17,Credit card,NaN,Billing statement,NaN,"My credit card statement from US Bank, XXXX. X...",Company chooses not to provide a public response,U.S. Bancorp,GA,305XX,Older American,Consent provided,Web,2015-07-17,Closed with monetary relief,Yes,No,1474177
4,2014-11-20,Credit card,NaN,Transaction issue,NaN,NaN,NaN,Bank of America,MA,02127,NaN,NaN,Web,2014-11-28,Closed with explanation,Yes,No,1132572

In [4]:
from datetime import datetime

In [5]:
df['Date received']=pd.to_datetime(df['Date received'])
df['Date sent to company']=pd.to_datetime(df['Date sent to company'])

In [6]:
df['Date_diff']=df['Date sent to company']-df['Date received']

In [7]:
df['Product'].value_counts()

Mortgage                   156175
Debt collection             86544
Credit reporting            81115
Credit card                 57358
Bank account or service     54403
Consumer Loan               18599
Student loan                14918
Money transfers              3349
Payday loan                  3219
Prepaid card                 2226
Other financial service       507
Virtual currency                8
Name: Product, dtype: int64

In [8]:
df['Pro_Morg']=np.where(df['Product']=='Mortgage',1,0)
df['Pro_dc']=np.where(df['Product']=='Debt collection',1,0)
df['Pro_cr']=np.where(df['Product']=='Credit reporting',1,0)
df['Pro_cc']=np.where(df['Product']=='Credit card',1,0)
df['Pro_bas']=np.where(df['Product']=='Bank account or service',1,0)
df['Pro_cl']=np.where(df['Product']=='Consumer Loan',1,0)
df['Pro_sl']=np.where(df['Product']=='Student loan',1,0)
df['Pro_mt']=np.where(df['Product']=='Money transfers',1,0)
df['Pro_pl']=np.where(df['Product']=='Payday loan',1,0)
df['Pro_pc']=np.where(df['Product']=='Prepaid card',1,0)

In [9]:
df['Sub-product'].isnull().sum()

138473

In [10]:
df=df.drop(['Product', 'Sub-product'],1)

In [11]:
df.head()

,Date received,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Consumer consent provided?,...,Pro_Morg,Pro_dc,Pro_cr,Pro_cc,Pro_bas,Pro_cl,Pro_sl,Pro_mt,Pro_pl,Pro_pc
0,2014-05-15,Billing statement,NaN,NaN,NaN,Wells Fargo & Company,MI,48342,Older American,NaN,...,0,0,0,1,0,0,0,0,0,0
1,2014-09-18,"Making/receiving payments, sending money",NaN,NaN,NaN,Santander Bank US,PA,18042,NaN,NaN,...,0,0,0,0,1,0,0,0,0,0
2,2014-03-13,Incorrect information on credit report,Account status,NaN,NaN,Equifax,CA,92427,NaN,NaN,...,0,0,1,0,0,0,0,0,0,0
3,2015-07-17,Billing statement,NaN,"My credit card statement from US Bank, XXXX. X...",Company chooses not to provide a public response,U.S. Bancorp,GA,305XX,Older American,Consent provided,...,0,0,0,1,0,0,0,0,0,0
4,2014-11-20,Transaction issue,NaN,NaN,NaN,Bank of America,MA,02127,NaN,NaN,...,0,0,0,1,0,0,0,0,0,0

In [12]:
df=df.drop(['Date received', 'Date sent to company'],1)

In [13]:
df.head()

,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Consumer consent provided?,Submitted via,...,Pro_Morg,Pro_dc,Pro_cr,Pro_cc,Pro_bas,Pro_cl,Pro_sl,Pro_mt,Pro_pl,Pro_pc
0,Billing statement,NaN,NaN,NaN,Wells Fargo & Company,MI,48342,Older American,NaN,Web,...,0,0,0,1,0,0,0,0,0,0
1,"Making/receiving payments, sending money",NaN,NaN,NaN,Santander Bank US,PA,18042,NaN,NaN,Referral,...,0,0,0,0,1,0,0,0,0,0
2,Incorrect information on credit report,Account status,NaN,NaN,Equifax,CA,92427,NaN,NaN,Referral,...,0,0,1,0,0,0,0,0,0,0
3,Billing statement,NaN,"My credit card statement from US Bank, XXXX. X...",Company chooses not to provide a public response,U.S. Bancorp,GA,305XX,Older American,Consent provided,Web,...,0,0,0,1,0,0,0,0,0,0
4,Transaction issue,NaN,NaN,NaN,Bank of America,MA,02127,NaN,NaN,Web,...,0,0,0,1,0,0,0,0,0,0

In [14]:
df['Issue'].nunique()

95

In [15]:
df['Issue'].value_counts()

Loan modification,collection,foreclosure    80302
Incorrect information on credit report      58527
Loan servicing, payments, escrow account    51403
Cont'd attempts collect debt not owed       36367
Account opening, closing, or management     23568
Disclosure verification of debt             16235
Communication tactics                       15312
Deposits and withdrawals                    14721
Application, originator, mortgage broker    11201
Billing disputes                             9600
Credit reporting company's investigation     9492
Other                                        9442
Managing the loan or lease                   8905
Problems caused by my funds being low        7758
False statements or representation           7074
Unable to get credit report/credit score     7060
Dealing with my lender or servicer           6460
Improper contact or sharing of info          6182
Problems when you are unable to pay          5921
Settlement process and costs                 5834
Taking/threatening an illegal action         5374
Identity theft / Fraud / Embezzlement        5141
Making/receiving payments, sending money     4618
Closing/Cancelling account                   4088
APR or interest rate                         3870
Credit decision / Underwriting               3755
Using a debit or ATM card                    3738
Can't repay my loan                          3668
Improper use of my credit report             3283
Repaying your loan                           2988
                                            ...
Application processing delay                  321
Can't stop charges to bank account            293
Payment to acct not credited                  266
Applied for loan/did not receive money        232
Arbitration                                   225
Sale of account                               223
Shopping for a line of credit                 202
Wrong amount charged or received              180
Charged bank acct wrong day or amt            164
Cash advance                                  163
Customer service/Customer relations           151
Overlimit fee                                 145
Adding money                                  143
Fees                                          142
Balance transfer fee                          141
Incorrect/missing disclosures or info         129
Cash advance fee                              128
Convenience checks                            100
Excessive fees                                 52
Unexpected/Other fees                          52
Advertising, marketing or disclosures          50
Lender repossessed or sold the vehicle         39
Overdraft, savings or rewards features         29
Disclosures                                    26
Lost or stolen money order                     25
Lost or stolen check                           20
Incorrect exchange rate                        13
Lender damaged or destroyed vehicle             5
Lender sold the property                        2
Lender damaged or destroyed property            1
Name: Issue, Length: 95, dtype: int64

In [16]:
for i in range(len(df.index)):
    if df['Issue'][i] in ['Lender damaged or destroyed property', 'Lender sold the property', 'Lender damaged or destroyed vehicle',
                      'Incorrect exchange rate', 'Lost or stolen check', 'Lost or stolen money order ', 'Disclosures', 'Overdraft, savings or rewards features',
                      'Lender repossessed or sold the vehicle', 'Advertising, marketing or disclosures','Unexpected/Other fees', 'Convenience checks',
                      'Incorrect/missing disclosures or info', 'Balance transfer fee', 'Fees','Adding money','Overlimit fee', 'Customer service/Customer relations',
                      'Cash advance', 'Charged bank acct wrong day or amt', 'Wrong amount charged or received']:
        df.loc[i,'Issue']='Other'

In [17]:
df['Issue'].value_counts()

Loan modification,collection,foreclosure    80302
Incorrect information on credit report      58527
Loan servicing, payments, escrow account    51403
Cont'd attempts collect debt not owed       36367
Account opening, closing, or management     23568
Disclosure verification of debt             16235
Communication tactics                       15312
Deposits and withdrawals                    14721
Application, originator, mortgage broker    11201
Other                                       11137
Billing disputes                             9600
Credit reporting company's investigation     9492
Managing the loan or lease                   8905
Problems caused by my funds being low        7758
False statements or representation           7074
Unable to get credit report/credit score     7060
Dealing with my lender or servicer           6460
Improper contact or sharing of info          6182
Problems when you are unable to pay          5921
Settlement process and costs                 5834
Taking/threatening an illegal action         5374
Identity theft / Fraud / Embezzlement        5141
Making/receiving payments, sending money     4618
Closing/Cancelling account                   4088
APR or interest rate                         3870
Credit decision / Underwriting               3755
Using a debit or ATM card                    3738
Can't repay my loan                          3668
Improper use of my credit report             3283
Repaying your loan                           2988
                                            ...
Other fee                                    1438
Credit reporting                             1358
Shopping for a loan or lease                 1170
Unsolicited issuance of credit card           993
Other transaction issues                      875
Collection practices                          805
Managing, opening, or closing account         759
Balance transfer                              726
Unauthorized transactions/trans. issues       695
Collection debt dispute                       690
Can't contact lender                          618
Money was not available when promised         597
Managing the line of credit                   535
Getting a loan                                436
Forbearance / Workout plans                   394
Account terms and changes                     372
Received a loan I didn't apply for            357
Other service issues                          335
Privacy                                       327
Bankruptcy                                    321
Application processing delay                  321
Can't stop charges to bank account            293
Payment to acct not credited                  266
Applied for loan/did not receive money        232
Arbitration                                   225
Sale of account                               223
Shopping for a line of credit                 202
Cash advance fee                              128
Excessive fees                                 52
Lost or stolen money order                     25
Name: Issue, Length: 75, dtype: int64

In [18]:
from sklearn.preprocessing import LabelEncoder

In [19]:
lbl_encod=LabelEncoder()
df['Issue']= lbl_encod.fit_transform(df['Issue'])

In [20]:
df['Sub-issue'].isnull().sum()

292625

In [21]:
df['Issue'].value_counts()

44    80302
42    58527
45    51403
21    36367
1     23568
33    16235
20    15312
32    14721
5     11201
52    11137
10     9600
28     9492
49     8905
59     7758
35     7074
71     7060
30     6460
40     6182
60     5921
65     5834
69     5374
39     5141
47     4618
17     4088
0      3870
23     3755
74     3738
13     3668
41     3283
62     2988
      ...
25     1438
27     1358
67     1170
73      993
55      875
19      805
50      759
8       726
72      695
18      690
12      618
51      597
48      535
38      436
36      394
2       372
61      357
54      335
58      327
9       321
4       321
14      293
56      266
6       232
7       225
64      223
66      202
15      128
34       52
46       25
Name: Issue, Length: 75, dtype: int64

In [22]:
df=df.drop(['Sub-issue'],1)

In [23]:
df['Consumer complaint narrative'].isnull().sum()

403327

In [24]:
for col in ['Consumer complaint narrative']:
    df[col]=df[col].astype("str")
df['User_narative']= df[['Consumer complaint narrative']].applymap(lambda x: 0 if x=='nan' else 1)
df['User_narative'].value_counts()

0    403327
1     75094
Name: User_narative, dtype: int64

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 478421 entries, 0 to 478420
Data columns (total 25 columns):
Issue                           478421 non-null int64
Consumer complaint narrative    478421 non-null object
Company public response         90392 non-null object
Company                         478421 non-null object
State                           474582 non-null object
ZIP code                        474573 non-null object
Tags                            67206 non-null object
Consumer consent provided?      135487 non-null object
Submitted via                   478421 non-null object
Company response to consumer    478421 non-null object
Timely response?                478421 non-null object
Consumer disputed?              478421 non-null object
Complaint ID                    478421 non-null int64
Date_diff                       478421 non-null timedelta64[ns]
Pro_Morg                        478421 non-null int32
Pro_dc                          478421 non-null int32
Pro_cr                          478421 non-null int32
Pro_cc                          478421 non-null int32
Pro_bas                         478421 non-null int32
Pro_cl                          478421 non-null int32
Pro_sl                          478421 non-null int32
Pro_mt                          478421 non-null int32
Pro_pl                          478421 non-null int32
Pro_pc                          478421 non-null int32
User_narative                   478421 non-null int64
dtypes: int32(10), int64(3), object(11), timedelta64[ns](1)
memory usage: 73.0+ MB

In [26]:
for col in ['Company public response']:
    df[col]=df[col].astype("str")

In [27]:
df['comp_narative']= df[['Company public response']].applymap(lambda x: 0 if x=='nan' else 1)
df['comp_narative'].value_counts()

0    388029
1     90392
Name: comp_narative, dtype: int64

In [28]:
df['Submitted via'].value_counts()

Web            313916
Referral        91352
Phone           34417
Postal mail     31448
Fax              7032
Email             256
Name: Submitted via, dtype: int64

In [29]:
dummy1= pd.get_dummies(df['Submitted via'], prefix='Sv')

In [30]:
df=pd.concat([df,dummy1],1)

In [31]:
df.head()

,Issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Consumer consent provided?,Submitted via,Company response to consumer,...,Pro_pl,Pro_pc,User_narative,comp_narative,Sv_Email,Sv_Fax,Sv_Phone,Sv_Postal mail,Sv_Referral,Sv_Web
0,11,nan,nan,Wells Fargo & Company,MI,48342,Older American,NaN,Web,Closed with explanation,...,0,0,0,0,0,0,0,0,0,1
1,47,nan,nan,Santander Bank US,PA,18042,NaN,NaN,Referral,Closed,...,0,0,0,0,0,0,0,0,1,0
2,42,nan,nan,Equifax,CA,92427,NaN,NaN,Referral,Closed with non-monetary relief,...,0,0,0,0,0,0,0,0,1,0
3,11,"My credit card statement from US Bank, XXXX. X...",Company chooses not to provide a public response,U.S. Bancorp,GA,305XX,Older American,Consent provided,Web,Closed with monetary relief,...,0,0,1,1,0,0,0,0,0,1
4,70,nan,nan,Bank of America,MA,02127,NaN,NaN,Web,Closed with explanation,...,0,0,0,0,0,0,0,0,0,1

In [32]:
df=df.drop(['Consumer complaint narrative','Company public response', 'Sv_Email','Submitted via' ],1)

In [33]:
df.head()

,Issue,Company,State,ZIP code,Tags,Consumer consent provided?,Company response to consumer,Timely response?,Consumer disputed?,Complaint ID,...,Pro_mt,Pro_pl,Pro_pc,User_narative,comp_narative,Sv_Fax,Sv_Phone,Sv_Postal mail,Sv_Referral,Sv_Web
0,11,Wells Fargo & Company,MI,48342,Older American,NaN,Closed with explanation,Yes,No,856103,...,0,0,0,0,0,0,0,0,0,1
1,47,Santander Bank US,PA,18042,NaN,NaN,Closed,Yes,No,1034666,...,0,0,0,0,0,0,0,0,1,0
2,42,Equifax,CA,92427,NaN,NaN,Closed with non-monetary relief,Yes,No,756363,...,0,0,0,0,0,0,0,0,1,0
3,11,U.S. Bancorp,GA,305XX,Older American,Consent provided,Closed with monetary relief,Yes,No,1474177,...,0,0,0,1,1,0,0,0,0,1
4,70,Bank of America,MA,02127,NaN,NaN,Closed with explanation,Yes,No,1132572,...,0,0,0,0,0,0,0,0,0,1

In [34]:
df.head()

,Issue,Company,State,ZIP code,Tags,Consumer consent provided?,Company response to consumer,Timely response?,Consumer disputed?,Complaint ID,...,Pro_mt,Pro_pl,Pro_pc,User_narative,comp_narative,Sv_Fax,Sv_Phone,Sv_Postal mail,Sv_Referral,Sv_Web
0,11,Wells Fargo & Company,MI,48342,Older American,NaN,Closed with explanation,Yes,No,856103,...,0,0,0,0,0,0,0,0,0,1
1,47,Santander Bank US,PA,18042,NaN,NaN,Closed,Yes,No,1034666,...,0,0,0,0,0,0,0,0,1,0
2,42,Equifax,CA,92427,NaN,NaN,Closed with non-monetary relief,Yes,No,756363,...,0,0,0,0,0,0,0,0,1,0
3,11,U.S. Bancorp,GA,305XX,Older American,Consent provided,Closed with monetary relief,Yes,No,1474177,...,0,0,0,1,1,0,0,0,0,1
4,70,Bank of America,MA,02127,NaN,NaN,Closed with explanation,Yes,No,1132572,...,0,0,0,0,0,0,0,0,0,1

In [35]:
df['State'].value_counts()

CA    70001
FL    46089
TX    35895
NY    32750
GA    21258
NJ    19369
PA    17109
IL    16947
VA    15613
MD    15281
OH    14831
NC    13347
MI    12377
AZ    10691
WA    10024
MA     9584
CO     8231
TN     7383
MO     6221
SC     6000
NV     5838
OR     5698
MN     5587
CT     5582
IN     5303
WI     5259
AL     4950
LA     4776
KY     3419
OK     3172
      ...
DE     2510
NH     2404
NM     2389
KS     2370
MS     2195
AR     2075
IA     1947
ID     1684
ME     1663
HI     1658
RI     1632
NE     1497
WV     1229
PR     1140
VT      804
MT      738
SD      631
AK      552
WY      459
ND      417
AE      195
AP      132
VI      121
GU       60
FM       30
MH       25
MP       15
AS       14
PW        9
AA        8
Name: State, Length: 62, dtype: int64

In [36]:
df.index

RangeIndex(start=0, stop=478421, step=1)

In [37]:
for i in range(len(df.index)):
    if df['State'][i] in ['AA','PW','AS','MP','MH','FM','GU']:
        df.loc[i,"State"]="OTHERS"

In [38]:
df['State'].value_counts()

CA        70001
FL        46089
TX        35895
NY        32750
GA        21258
NJ        19369
PA        17109
IL        16947
VA        15613
MD        15281
OH        14831
NC        13347
MI        12377
AZ        10691
WA        10024
MA         9584
CO         8231
TN         7383
MO         6221
SC         6000
NV         5838
OR         5698
MN         5587
CT         5582
IN         5303
WI         5259
AL         4950
LA         4776
KY         3419
OK         3172
DC         2786
UT         2608
DE         2510
NH         2404
NM         2389
KS         2370
MS         2195
AR         2075
IA         1947
ID         1684
ME         1663
HI         1658
RI         1632
NE         1497
WV         1229
PR         1140
VT          804
MT          738
SD          631
AK          552
WY          459
ND          417
AE          195
OTHERS      161
AP          132
VI          121
Name: State, dtype: int64

In [39]:
df['State']=df['State'].astype('str')
state_encod=LabelEncoder()
df['State']= state_encod.fit_transform(df['State'])

In [40]:
df.State.value_counts()

6     70001
11    46089
47    35895
36    32750
12    21258
33    19369
41    17109
16    16947
49    15613
22    15281
37    14831
29    13347
24    12377
5     10691
52    10024
21     9584
7      8231
46     7383
26     6221
44     6000
35     5838
39     5698
25     5587
8      5582
17     5303
53     5259
2      4950
20     4776
56     3839
19     3419
38     3172
9      2786
48     2608
10     2510
32     2404
34     2389
18     2370
27     2195
4      2075
14     1947
15     1684
23     1663
13     1658
43     1632
31     1497
54     1229
42     1140
51      804
28      738
45      631
1       552
55      459
30      417
0       195
40      161
3       132
50      121
Name: State, dtype: int64

In [41]:
df=df.drop(['ZIP code'],1)

In [42]:
df['Tags']= df['Tags'].astype('str')
df['Tags'].value_counts()

nan                              411215
Older American                    39064
Servicemember                     22592
Older American, Servicemember      5550
Name: Tags, dtype: int64

In [43]:
dummy3=pd.get_dummies(df['Tags'])

In [44]:
dummy3.head()

   Older American  Older American, Servicemember  Servicemember  nan
0               1                              0              0    0
1               0                              0              0    1
2               0                              0              0    1
3               1                              0              0    0
4               0                              0              0    1

In [45]:
df=pd.concat([df,dummy3],1)

In [46]:
df.head()

,Issue,Company,State,Tags,Consumer consent provided?,Company response to consumer,Timely response?,Consumer disputed?,Complaint ID,Date_diff,...,comp_narative,Sv_Fax,Sv_Phone,Sv_Postal mail,Sv_Referral,Sv_Web,Older American,"Older American, Servicemember",Servicemember,nan
0,11,Wells Fargo & Company,24,Older American,NaN,Closed with explanation,Yes,No,856103,1 days,...,0,0,0,0,0,1,1,0,0,0
1,47,Santander Bank US,41,nan,NaN,Closed,Yes,No,1034666,6 days,...,0,0,0,0,1,0,0,0,0,1
2,42,Equifax,6,nan,NaN,Closed with non-monetary relief,Yes,No,756363,21 days,...,0,0,0,0,1,0,0,0,0,1
3,11,U.S. Bancorp,12,Older American,Consent provided,Closed with monetary relief,Yes,No,1474177,0 days,...,1,0,0,0,0,1,1,0,0,0
4,70,Bank of America,21,nan,NaN,Closed with explanation,Yes,No,1132572,8 days,...,0,0,0,0,0,1,0,0,0,1

In [47]:
df=df.drop(['Older American, Servicemember','Tags'],1)

In [48]:
df.head()

,Issue,Company,State,Consumer consent provided?,Company response to consumer,Timely response?,Consumer disputed?,Complaint ID,Date_diff,Pro_Morg,...,User_narative,comp_narative,Sv_Fax,Sv_Phone,Sv_Postal mail,Sv_Referral,Sv_Web,Older American,Servicemember,nan
0,11,Wells Fargo & Company,24,NaN,Closed with explanation,Yes,No,856103,1 days,0,...,0,0,0,0,0,0,1,1,0,0
1,47,Santander Bank US,41,NaN,Closed,Yes,No,1034666,6 days,0,...,0,0,0,0,0,1,0,0,0,1
2,42,Equifax,6,NaN,Closed with non-monetary relief,Yes,No,756363,21 days,0,...,0,0,0,0,0,1,0,0,0,1
3,11,U.S. Bancorp,12,Consent provided,Closed with monetary relief,Yes,No,1474177,0 days,0,...,1,1,0,0,0,0,1,1,0,0
4,70,Bank of America,21,NaN,Closed with explanation,Yes,No,1132572,8 days,0,...,0,0,0,0,0,0,1,0,0,1

In [49]:
df['Consumer consent provided?'].isnull().sum()

342934

In [50]:
df['Consumer consent provided?']=df['Consumer consent provided?'].astype("str")

In [51]:
df['Consumer consent provided?'].value_counts()

nan                     342934
Consent provided         75095
Consent not provided     56147
Other                     4242
Consent withdrawn            3
Name: Consumer consent provided?, dtype: int64

In [52]:
dummy4=pd.get_dummies(df['Consumer consent provided?'],prefix='Ccp')

In [53]:
dummy4.head()

,Ccp_Consent not provided,Ccp_Consent provided,Ccp_Consent withdrawn,Ccp_Other,Ccp_nan
0,0,0,0,0,1
1,0,0,0,0,1
2,0,0,0,0,1
3,0,1,0,0,0
4,0,0,0,0,1

In [54]:
df=pd.concat([df,dummy4],1)

In [55]:
df=df.drop(['Ccp_Consent withdrawn','Consumer consent provided?'],1)

In [56]:
df['Company response to consumer'].value_counts()

Closed with explanation            354310
Closed with non-monetary relief     61491
Closed with monetary relief         32925
Closed without relief               14145
Closed                              11365
Closed with relief                   4184
Untimely response                       1
Name: Company response to consumer, dtype: int64

In [57]:
df['Company response to consumer']=df['Company response to consumer'].astype("str")

In [58]:
df['Company response to consumer'].value_counts()

Closed with explanation            354310
Closed with non-monetary relief     61491
Closed with monetary relief         32925
Closed without relief               14145
Closed                              11365
Closed with relief                   4184
Untimely response                       1
Name: Company response to consumer, dtype: int64

In [59]:
dummy5=pd.get_dummies(df['Company response to consumer'],prefix='comp_resp')

In [60]:
dummy5.head()

,comp_resp_Closed,comp_resp_Closed with explanation,comp_resp_Closed with monetary relief,comp_resp_Closed with non-monetary relief,comp_resp_Closed with relief,comp_resp_Closed without relief,comp_resp_Untimely response
0,0,1,0,0,0,0,0
1,1,0,0,0,0,0,0
2,0,0,0,1,0,0,0
3,0,0,1,0,0,0,0
4,0,1,0,0,0,0,0

In [61]:
df=pd.concat([df,dummy5],1)

In [62]:
df=df.drop(['Company response to consumer','comp_resp_Untimely response','comp_resp_Closed without relief'],1)

In [63]:
df.head()

,Issue,Company,State,Timely response?,Consumer disputed?,Complaint ID,Date_diff,Pro_Morg,Pro_dc,Pro_cr,...,nan,Ccp_Consent not provided,Ccp_Consent provided,Ccp_Other,Ccp_nan,comp_resp_Closed,comp_resp_Closed with explanation,comp_resp_Closed with monetary relief,comp_resp_Closed with non-monetary relief,comp_resp_Closed with relief
0,11,Wells Fargo & Company,24,Yes,No,856103,1 days,0,0,0,...,0,0,0,0,1,0,1,0,0,0
1,47,Santander Bank US,41,Yes,No,1034666,6 days,0,0,0,...,1,0,0,0,1,1,0,0,0,0
2,42,Equifax,6,Yes,No,756363,21 days,0,0,1,...,1,0,0,0,1,0,0,0,1,0
3,11,U.S. Bancorp,12,Yes,No,1474177,0 days,0,0,0,...,0,0,1,0,0,0,0,1,0,0
4,70,Bank of America,21,Yes,No,1132572,8 days,0,0,0,...,1,0,0,0,1,0,1,0,0,0

In [64]:
df.Company.value_counts()

Bank of America                            46336
Wells Fargo & Company                      35453
JPMorgan Chase & Co.                       28852
Equifax                                    28832
Experian                                   26794
TransUnion Intermediate Holdings, Inc.     22508
Citibank                                   22300
Ocwen                                      17475
Capital One                                13396
Nationstar Mortgage                        11278
Synchrony Financial                         8299
U.S. Bancorp                                8201
Ditech Financial LLC                        7624
Navient Solutions, Inc.                     7375
PNC Bank N.A.                               5801
Encore Capital Group                        5248
Amex                                        5163
HSBC North America Holdings Inc.            5131
SunTrust Banks, Inc.                        4133
Discover                                    4127
TD Bank US Holding Company                  3879
Select Portfolio Servicing, Inc             3731
Portfolio Recovery Associates, Inc.         3079
Citizens Financial Group, Inc.              2607
Seterus, Inc.                               2465
Barclays PLC                                2445
Fifth Third Financial Corporation           2414
ERC                                         2320
BB&T Financial                              2216
M&T Bank Corporation                        2130
                                           ...
Tecco Systems                                  1
Jayandbee, Inc.                                1
Zenith Financial Mortgage Company, Inc.        1
Schiller & Adam, P.A.                          1
Alpine Mortgage Services, LLC                  1
Drew Eckl & Farnham, LLP                       1
Cunningham Law Inc.                            1
Professional Recovery of Longmont, Inc.        1
Capitol Credit Services, Inc                   1
MDC Holdings, INC                              1
Investment Management Company, LLC             1
Wheel City Motors East, Inc.                   1
Platinum Finance Company, LLC                  1
Columbus Capital Lending, LLC                  1
Credit Collection Partners, Inc.               1
Rapid Mortgage                                 1
Certified Bureau of the South, Inc             1
Zions First National Bank                      1
Ivan Brown                                     1
Firsel Law Group, Ltd.                         1
South Exchange Inc                             1
Citizens First Wholesale Mortgage Co.          1
1st Portfolio Holding Corporation              1
Phelan Hallinan & Jones, LLC                   1
Mortgage Network Solutions LLC                 1
Priority Funding LLC                           1
MEMA CORP                                      1
Clifton Mortgage Services, LLC                 1
Jzanus Ltd.                                    1
Randolph, Boyd, Cherry and Vaughan             1
Name: Company, Length: 3276, dtype: int64

In [65]:
df['Timely response?'].value_counts()

Yes    470277
No       8144
Name: Timely response?, dtype: int64

In [66]:
df['Tr_yes']=np.where(df['Timely response?']=='Yes',1,0)

In [67]:
df['Tr_yes'].value_counts()

1    470277
0      8144
Name: Tr_yes, dtype: int64

In [68]:
df['Consumer disputed?'].value_counts()

No     376990
Yes    101431
Name: Consumer disputed?, dtype: int64

In [69]:
df['Consumer_disp_y']=np.where(df['Consumer disputed?']=='Yes',1,0)

In [70]:
df.head()

,Issue,Company,State,Timely response?,Consumer disputed?,Complaint ID,Date_diff,Pro_Morg,Pro_dc,Pro_cr,...,Ccp_Consent provided,Ccp_Other,Ccp_nan,comp_resp_Closed,comp_resp_Closed with explanation,comp_resp_Closed with monetary relief,comp_resp_Closed with non-monetary relief,comp_resp_Closed with relief,Tr_yes,Consumer_disp_y
0,11,Wells Fargo & Company,24,Yes,No,856103,1 days,0,0,0,...,0,0,1,0,1,0,0,0,1,0
1,47,Santander Bank US,41,Yes,No,1034666,6 days,0,0,0,...,0,0,1,1,0,0,0,0,1,0
2,42,Equifax,6,Yes,No,756363,21 days,0,0,1,...,0,0,1,0,0,0,1,0,1,0
3,11,U.S. Bancorp,12,Yes,No,1474177,0 days,0,0,0,...,1,0,0,0,0,1,0,0,1,0
4,70,Bank of America,21,Yes,No,1132572,8 days,0,0,0,...,0,0,1,0,1,0,0,0,1,0

In [71]:
df=df.drop(['Consumer disputed?','Timely response?'],1)

In [72]:
df['Date_diff']=df['Date_diff'].astype('str')

In [73]:
df['Date_diff'].head(10)

0     1 days 00:00:00.000000000
1     6 days 00:00:00.000000000
2    21 days 00:00:00.000000000
3     0 days 00:00:00.000000000
4     8 days 00:00:00.000000000
5     5 days 00:00:00.000000000
6     3 days 00:00:00.000000000
7     0 days 00:00:00.000000000
8     1 days 00:00:00.000000000
9     2 days 00:00:00.000000000
Name: Date_diff, dtype: object

In [74]:
import string

In [75]:
df['Date_diff']=[x.replace("days 00:00:00.000000000","") for x in df['Date_diff']]

In [76]:
df['Date_diff'].head()

0     1
1     6
2    21
3     0
4     8
Name: Date_diff, dtype: object

In [77]:
df['Date_diff']= pd.to_numeric(df['Date_diff'], errors='coerce')

In [78]:
df_sub_copy = df.copy()

In [79]:
df['Company']=df['Company'].astype('str')
Company_encod=LabelEncoder()
df['Company']= Company_encod.fit_transform(df['Company'])

In [80]:
id=df['Complaint ID']

In [81]:
df=df.drop(['Complaint ID'],1)

In [82]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df,df['Consumer_disp_y'],test_size=.20, random_state=1)
X_train=X_train.drop(['Consumer_disp_y'],1)
X_test=X_test.drop(['Consumer_disp_y'],1)

In [83]:
X_train.columns

Index(['Issue', 'Company', 'State', 'Date_diff', 'Pro_Morg', 'Pro_dc',
       'Pro_cr', 'Pro_cc', 'Pro_bas', 'Pro_cl', 'Pro_sl', 'Pro_mt', 'Pro_pl',
       'Pro_pc', 'User_narative', 'comp_narative', 'Sv_Fax', 'Sv_Phone',
       'Sv_Postal mail', 'Sv_Referral', 'Sv_Web', 'Older American',
       'Servicemember', 'nan', 'Ccp_Consent not provided',
       'Ccp_Consent provided', 'Ccp_Other', 'Ccp_nan', 'comp_resp_Closed',
       'comp_resp_Closed with explanation',
       'comp_resp_Closed with monetary relief',
       'comp_resp_Closed with non-monetary relief',
       'comp_resp_Closed with relief', 'Tr_yes'],
      dtype='object')

In [84]:
import xgboost as xgb
from sklearn.model_selection import GridSearchCV 
from xgboost.sklearn import XGBClassifier

0    301661
1     81075
Name: Consumer_disp_y, dtype: int64

In [85]:
param_test1 = {
 'max_depth':np.arange(3,10,2),
 'min_child_weight':np.arange(1,6,2)
}
gsearch1 = GridSearchCV(estimator = XGBClassifier( learning_rate =0.1, n_estimators=140, max_depth=5,
 min_child_weight=1, gamma=0, subsample=0.8, colsample_bytree=0.8,
 objective= 'binary:logistic', nthread=4, scale_pos_weight=1, seed=27), 
 param_grid = param_test1, scoring='roc_auc',n_jobs=4,iid=False, cv=5)
gsearch1.fit(X_train,y_train)
gsearch1.grid_scores_, gsearch1.best_params_, gsearch1.best_score_

C:\Users\DX\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:667: DeprecationWarning: The grid_scores_ attribute was deprecated in version 0.18 in favor of the more elaborate cv_results_ attribute. The grid_scores_ attribute will not be available from 0.20
  DeprecationWarning)

([mean: 0.62191, std: 0.00179, params: {'max_depth': 3, 'min_child_weight': 1},
  mean: 0.62195, std: 0.00173, params: {'max_depth': 3, 'min_child_weight': 3},
  mean: 0.62208, std: 0.00169, params: {'max_depth': 3, 'min_child_weight': 5},
  mean: 0.62979, std: 0.00133, params: {'max_depth': 5, 'min_child_weight': 1},
  mean: 0.62991, std: 0.00124, params: {'max_depth': 5, 'min_child_weight': 3},
  mean: 0.62997, std: 0.00120, params: {'max_depth': 5, 'min_child_weight': 5},
  mean: 0.63342, std: 0.00119, params: {'max_depth': 7, 'min_child_weight': 1},
  mean: 0.63397, std: 0.00095, params: {'max_depth': 7, 'min_child_weight': 3},
  mean: 0.63360, std: 0.00052, params: {'max_depth': 7, 'min_child_weight': 5},
  mean: 0.63325, std: 0.00130, params: {'max_depth': 9, 'min_child_weight': 1},
  mean: 0.63368, std: 0.00080, params: {'max_depth': 9, 'min_child_weight': 3},
  mean: 0.63423, std: 0.00084, params: {'max_depth': 9, 'min_child_weight': 5}],
 {'max_depth': 9, 'min_child_weight': 5},
 0.63422644251512117)

In [ ]:
"""param_test2={
 'max_depth':np.arange(3,10,2),
 'min_child_weight':np.arange(1,6,2)
}
gsearch1 = GridSearchCV(estimator = XGBClassifier( learning_rate =0.1, n_estimators=140, max_depth=5,
 min_child_weight=1, gamma=0, subsample=0.8, colsample_bytree=0.8,
 objective= 'binary:logistic', nthread=4, scale_pos_weight=1, seed=27), 
 param_grid = param_test1, scoring='roc_auc',n_jobs=4,iid=False, cv=5)
gsearch1.fit(X_train,y_train)
gsearch1.grid_scores_, gsearch1.best_params_, gsearch1.best_score_"""

In [105]:
from sklearn.tree import DecisionTreeClassifier

In [99]:
final_fit=XGBClassifier( learning_rate =0.1, n_estimators=140, max_depth=9,
 min_child_weight=5, gamma=0, subsample=0.8, colsample_bytree=0.8,
 objective= 'binary:logistic', nthread=4, scale_pos_weight=1, seed=27)

In [106]:
clf = DecisionTreeClassifier()

ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

In [100]:
final_fit.fit(X_train,y_train)

XGBClassifier(base_score=0.5, colsample_bylevel=1, colsample_bytree=0.8,
       gamma=0, learning_rate=0.1, max_delta_step=0, max_depth=9,
       min_child_weight=5, missing=None, n_estimators=140, nthread=4,
       objective='binary:logistic', reg_alpha=0, reg_lambda=1,
       scale_pos_weight=1, seed=27, silent=True, subsample=0.8)

In [88]:
predict=final_fit.predict(X_test)

In [89]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [102]:
print (confusion_matrix(predict,y_test))

[[75329 20356]
 [    0     0]]

In [103]:
print(classification_report(y_test, predict))

             precision    recall  f1-score   support

          0       0.79      1.00      0.88     75329
          1       0.00      0.00      0.00     20356

avg / total       0.62      0.79      0.69     95685

In [92]:
test_data=pd.read_csv('Consumer_Complaints_test_share.csv')

In [93]:
test_data.head()

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Consumer consent provided?,Submitted via,Date sent to company,Company response to consumer,Timely response?,Complaint ID
0,2014-01-18,Bank account or service,Cashing a check without an account,Deposits and withdrawals,NaN,NaN,NaN,Bank of America,CA,95691,NaN,NaN,Web,2014-01-17,Closed with explanation,Yes,675956
1,2016-03-31,Debt collection,Credit card,Cont'd attempts collect debt not owed,Debt was paid,NaN,NaN,"National Credit Adjusters, LLC",FL,32086,NaN,Consent not provided,Web,2016-03-31,Closed with explanation,Yes,1858795
2,2012-03-08,Mortgage,Conventional adjustable mortgage (ARM),"Loan servicing, payments, escrow account",NaN,NaN,NaN,Wells Fargo & Company,CA,94618,NaN,NaN,Web,2012-03-09,Closed without relief,Yes,32637
3,2016-01-07,Credit reporting,NaN,Unable to get credit report/credit score,Problem getting report or credit score,NaN,Company chooses not to provide a public response,"TransUnion Intermediate Holdings, Inc.",FL,33584,Older American,NaN,Postal mail,2016-01-12,Closed with non-monetary relief,Yes,1731374
4,2013-08-23,Mortgage,FHA mortgage,"Loan modification,collection,foreclosure",NaN,NaN,NaN,Bank of America,FL,33543,NaN,NaN,Web,2013-08-23,Closed with explanation,Yes,501487

In [94]:
test_data['Date received']=pd.to_datetime(test_data['Date received'])
test_data['Date sent to company']=pd.to_datetime(test_data['Date sent to company'])
test_data['Date_diff']=test_data['Date sent to company']-test_data['Date received']
test_data=test_data.drop(['Date received', 'Date sent to company'],1)
test_data['Pro_Morg']=np.where(test_data['Product']=='Mortgage',1,0)
test_data['Pro_dc']=np.where(test_data['Product']=='Debt collection',1,0)
test_data['Pro_cr']=np.where(test_data['Product']=='Credit reporting',1,0)
test_data['Pro_cc']=np.where(test_data['Product']=='Credit card',1,0)
test_data['Pro_bas']=np.where(test_data['Product']=='Bank account or service',1,0)
test_data['Pro_cl']=np.where(test_data['Product']=='Consumer Loan',1,0)
test_data['Pro_sl']=np.where(test_data['Product']=='Student loan',1,0)
test_data['Pro_mt']=np.where(test_data['Product']=='Money transfers',1,0)
test_data['Pro_pl']=np.where(test_data['Product']=='Payday loan',1,0)
test_data['Pro_pc']=np.where(test_data['Product']=='Prepaid card',1,0)
test_data=test_data.drop(['Product', 'Sub-product'],1)
for i in range(len(test_data['Complaint ID'].index)):
    if test_data['Issue'][i] in ['Lender damaged or destroyed property', 'Lender sold the property', 'Lender damaged or destroyed vehicle',
                      'Incorrect exchange rate', 'Lost or stolen check', 'Lost or stolen money order ', 'Disclosures', 'Overdraft, savings or rewards features',
                      'Lender repossessed or sold the vehicle', 'Advertising, marketing or disclosures','Unexpected/Other fees', 'Convenience checks',
                      'Incorrect/missing disclosures or info', 'Balance transfer fee', 'Fees','Adding money','Overlimit fee', 'Customer service/Customer relations',
                      'Cash advance', 'Charged bank acct wrong day or amt', 'Wrong amount charged or received']:
        test_data.loc[i,'Issue']='Other'
lbl_encod=LabelEncoder()
test_data['Issue']= lbl_encod.fit_transform(test_data['Issue'])
test_data=test_data.drop(['Sub-issue'],1)
for col in ['Consumer complaint narrative']:
    test_data[col]=test_data[col].astype("str")
test_data['User_narative']= test_data[['Consumer complaint narrative']].applymap(lambda x: 0 if x=='nan' else 1)
for col in ['Company public response']:
    test_data[col]=test_data[col].astype("str")
test_data['comp_narative']= test_data[['Company public response']].applymap(lambda x: 0 if x=='nan' else 1)
dummy1= pd.get_dummies(test_data['Submitted via'], prefix='Sv')
test_data=pd.concat([test_data,dummy1],1)
test_data=test_data.drop(['Consumer complaint narrative','Company public response', 'Sv_Email','Submitted via' ],1)
for i in range(len(test_data.index)):
    if test_data['State'][i] in ['AA','PW','AS','MP','MH','FM','GU']:
        test_data.loc[i,"State"]="OTHERS"
test_data['State']=test_data['State'].astype('str')
state_encod=LabelEncoder()
test_data['State']= state_encod.fit_transform(test_data['State'])
test_data=test_data.drop(['ZIP code'],1)
test_data['Tags']= test_data['Tags'].astype('str')
dummy3=pd.get_dummies(test_data['Tags'])
test_data=pd.concat([test_data,dummy3],1)
test_data=test_data.drop(['Older American, Servicemember','Tags'],1)
test_data['Consumer consent provided?']=test_data['Consumer consent provided?'].astype("str")
dummy4=pd.get_dummies(test_data['Consumer consent provided?'],prefix='Ccp')
test_data=pd.concat([test_data,dummy4],1)
test_data=test_data.drop(['Ccp_Consent withdrawn','Consumer consent provided?'],1)
test_data['Company response to consumer']=test_data['Company response to consumer'].astype("str")
dummy5=pd.get_dummies(test_data['Company response to consumer'],prefix='comp_resp')
test_data=pd.concat([test_data,dummy5],1)
test_data=test_data.drop(['Company response to consumer','comp_resp_Untimely response','comp_resp_Closed without relief'],1)
test_data['Tr_yes']=np.where(test_data['Timely response?']=='Yes',1,0)
test_data=test_data.drop(['Timely response?'],1)
test_data['Date_diff']=test_data['Date_diff'].astype('str')
import string
test_data['Date_diff']=[x.replace("days 00:00:00.000000000","") for x in test_data['Date_diff']]
test_data['Date_diff']= pd.to_numeric(test_data['Date_diff'], errors='coerce')
test_data['Company']=test_data['Company'].astype('str')
Company_encod=LabelEncoder()
test_data['Company']= Company_encod.fit_transform(test_data['Company'])
id1=test_data['Complaint ID']
test_data=test_data.drop(['Complaint ID'],1)

In [95]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119606 entries, 0 to 119605
Data columns (total 34 columns):
Issue                                        119606 non-null int64
Company                                      119606 non-null int64
State                                        119606 non-null int64
Date_diff                                    118193 non-null float64
Pro_Morg                                     119606 non-null int32
Pro_dc                                       119606 non-null int32
Pro_cr                                       119606 non-null int32
Pro_cc                                       119606 non-null int32
Pro_bas                                      119606 non-null int32
Pro_cl                                       119606 non-null int32
Pro_sl                                       119606 non-null int32
Pro_mt                                       119606 non-null int32
Pro_pl                                       119606 non-null int32
Pro_pc                                       119606 non-null int32
User_narative                                119606 non-null int64
comp_narative                                119606 non-null int64
Sv_Fax                                       119606 non-null uint8
Sv_Phone                                     119606 non-null uint8
Sv_Postal mail                               119606 non-null uint8
Sv_Referral                                  119606 non-null uint8
Sv_Web                                       119606 non-null uint8
Older American                               119606 non-null uint8
Servicemember                                119606 non-null uint8
nan                                          119606 non-null uint8
Ccp_Consent not provided                     119606 non-null uint8
Ccp_Consent provided                         119606 non-null uint8
Ccp_Other                                    119606 non-null uint8
Ccp_nan                                      119606 non-null uint8
comp_resp_Closed                             119606 non-null uint8
comp_resp_Closed with explanation            119606 non-null uint8
comp_resp_Closed with monetary relief        119606 non-null uint8
comp_resp_Closed with non-monetary relief    119606 non-null uint8
comp_resp_Closed with relief                 119606 non-null uint8
Tr_yes                                       119606 non-null int32
dtypes: float64(1), int32(11), int64(5), uint8(17)
memory usage: 12.4 MB

In [96]:
predict_test=final_fit.predict(test_data)

In [98]:
predict_test

array([0, 0, 0, ..., 0, 0, 0])